fix: validate only universal release APK

diff --git a/.github/workflows/debug_build.yml b/.github/workflows/debug_build.yml
--- a/.github/workflows/debug_build.yml
+++ b/.github/workflows/debug_build.yml
@@ -69,12 +69,12 @@ jobs:
           fi
 
           echo "Validating APKs"
-          for abi in universal arm64-v8a armeabi-v7a x86_64 x86; do
-            if ! test -f "$APK_DIR_PATH/${APK_BASENAME_PREFIX}_$abi.apk"; then
-              files_found="$(ls "$APK_DIR_PATH")"
-              exit_on_error "Failed to find built APK at '$APK_DIR_PATH/${APK_BASENAME_PREFIX}_$abi.apk'. Files found: "$'\n'"$files_found"
-            fi
-          done
+#          for abi in universal arm64-v8a armeabi-v7a x86_64 x86; do
+#            if ! test -f "$APK_DIR_PATH/${APK_BASENAME_PREFIX}_$abi.apk"; then
+#              files_found="$(ls "$APK_DIR_PATH")"
+#              exit_on_error "Failed to find built APK at '$APK_DIR_PATH/${APK_BASENAME_PREFIX}_$abi.apk'. Files found: "$'\n'"$files_found"
+#            fi
+#          done
 
           echo "Generating sha25sums file"
           if ! (cd "$APK_DIR_PATH"; sha256sum \
